### PR TITLE
Designation of B.1.13, B.1.14, A.2.3, and A.3

### LINKED ISSUE #24: Proposal for B.1 lineage with G175093A [35 seqs, 33x USA, 1x UK, 1x Germany]
This is the largest branch on the tree, not counting already labeled lineages.
https://nextstrain.org/groups/illinois-gagnon-private/monkeypox/0928

image

image

This mutation carries the amino acid change OPG204: D188N

Earliest sample with firm date: 6/17/2022
Latest sample with firm date: 8/04/2022 (The german sample has only 08/2022 as a collection date)

All but one of the samples have secondary mutation C132520T. There are another two samples with G175093A but without C132520T, but they've been sorted elsewhere on the tree. They are hMPX/Human/USA/CA-LAC-PHL-MA00092 and MA00096.

### LINKED ISSUE #25: Proposal for an A.2 sublineage sequenced in USA-TX and Portugal
There's another cluster of 2 sequences in A.2, similar to A.2.1 and A.2.2:
image

https://nextstrain.org/staging/monkeypox/hmpxv1/big?m=div

I propose to designate this as A.2.3

Defining mutations:
Unique: G2752A, C57284T, C74226T, G118739A, C146223T, G170317A, G172527A, C175759T, G189417A, C189474T
Homoplasies: G39173A, G61844A, G148427A, G150800A, G168365A

Sequences: ON676707, OP555515

### LINKED ISSUE #27: Proposal for a B.1 sublineage with defining mut C159779T (Germany, France, Sweden, Portugal, US)
There's another candidate for a B.1 lineage designation with defining mutation C159779T (unique so far, good sign!) with detected circulation in 5 countries: Germany, France, Sweden, Portugal, US

image

https://nextstrain.org/staging/monkeypox/hmpxv1/big?c=gt-nuc_159779&m=div

### PR DESCRIPTION
**Pull request by corneliusroemer**
- Broaden B.1.11 to include MN-MDH-MPXV_0001
- Add yml and md file for designations 2022-10-31

Clades can be seen on this build: https://next.nextstrain.org/staging/monkeypox/hmpxv1

Resolves #24 
Resolves #25
Resovles #26 
Resolves #27

### CODE REVIEW

**Review by AngieHinrichs — APPROVED** [review]
Looks good, thanks Cornelius!

**Review by emmahodcroft — APPROVED** [review]

**Comment by emmahodcroft** [comment]
Thanks @corneliusroemer for pulling this together. I went through each of these and they seem sensible and useful, and the descriptions in the designation record are thorough and accurate. 

I think it's good!

**Review by vmmborges — APPROVED** [review]

**Comment by emmahodcroft** [comment]
Shall we merge this in tomorrow Cornelius? Is there anything else on the checklist? I don't think so - but let me know if I'm wrong!

**Comment by corneliusroemer** [comment]
Yep, it's merged, I'm prepping the dataset just now @emmahodcroft

**Comment by corneliusroemer** [comment]
Datasets are now on master.clades.nextstrain.org

And can also be tested via specific URLs in https://github.com/nextstrain/nextclade_data/pull/46

**Pull request merged**
